import { Assembler } from "./assembler.js";

const assembler = new Assembler();

let code_line = [
    "MOV A,B",
    "BCD",
    // "LXI B,    2323",
    // "MVI A, 1250",
    // "ADI 13",
    // "ORI 14",
    // "XRI 15",
    // "MVI E, 16",
    // "MVI H, 17",
    // "MVI L, 18",
    // "MVI M, 19",
    // "JC 1250",
    // "JM 1350",
    // "JP 1450",
    // "JPE 1550",
    // "JPO 1650",
    // "JZ 1750",
    // "JNZ 1850",
    // "JMP 1950",
    // "LDA 4560",
    // "DAA",
    // "NOP",
    // "HLT",
    // "LDAX B",
    // "LDAX D",
    // "LDAX H",
    // "STAX B",
    // "STAX D",
    // "STAX H",
    // "XCHG",
    // "XTHL",
    // "SPHL",
    // "PCHL",
    // "CMA",
    // "CMC",
    // "STC",
    // "DI",
    // "EI",
    // "RIM",
    // "SIM",
    // "RC",
    // "RNC",
    // "RP",
    // "RM",
    // "RZ",
    // "RNZ",
    // "RPE",
    // "RPO",
    // "RET",
    // "RLC",
    // "RRC",
    // "RAL",
    // "RAR",
    // "DAD B",
    // "DAD D",
    // "DAD H",
    // "DAD SP",
    // "RST 0",
    // "RST 1",
    // "RST 2",
    // "RST 3",
    // "RST 4",
    // "RST 5",
    // "RST 6",
    // "RST 7",
    // "CMP B",
    // "CMP A",
    // "CMP H",
    // "DCR B",
    // "DCR A",
    // "DCR H",
    // "LXI B, 2323",
    // "PUSH B",
    // "PUSH D",
    // "PUSH H",
    // "PUSH PSW",
    // "INR B",
    // "INR A",
    // "INR H",
    // "LXI B, 2324",
    // "DCX B",
    // "DCX D",
    // "DCX H",
    // "DCX SP",
    //"LXI SP, 2526",
    // "INX B",
    // "INX D",
    // "INX H",
    // "INX SP",
    // "CALL 4590",
    // "CZ 1234",
    // "CPI 88",
    // "IN 45",
    // "OUT 90",
    // "LHLD 1234",
    // "SHLD 5678",
    // "STA 1000",
    // "HLT"
];
let output = assembler.converter(code_line);

console.log(output);

